import { defineConfig } from 'vitepress'
import { nav, sidebar, type SidebarCopy, type NavCopy } from './shared'

const copy: SidebarCopy & NavCopy = {
  guide: '指南',
  selfHosting: '部署',
  integration: '接入',
  reference: '參考',
  introduction: '簡介',
  features: '功能',
  concepts: '運作方式',
  docker: 'Docker 部署',
  proxy: '反向代理',
  admin: '管理後台',
  notifications: '通知',
  captcha: '人機驗證',
  backup: '備份與還原',
  upgrade: '升級',
  twikoo: '從 Twikoo 遷移',
  faq: '常見問題',
  html: 'HTML 接入',
  sdk: 'JavaScript SDK',
  hugo: 'Hugo PaperMod',
  customCss: '自訂樣式',
  smoji: 'Smoji 貼圖包',
  configuration: '設定參考',
  cli: '命令列',
  api: 'REST API',
  internalVersions: '內測記錄（請勿使用）',
  earlierVersions: '更早的候選版本',
  versionCurrent: 'v0.4.0',
  versionLatest: '（最新）',
}

export const zhHant = defineConfig({
  title: 'Ecoku',
  description: '自託管，多站點，專注文字討論。',
  lang: 'zh-Hant',
  markdown: {
    container: {
      tipLabel: '提示',
      warningLabel: '注意',
      dangerLabel: '警告',
      infoLabel: '說明',
      detailsLabel: '詳細資訊',
    },
  },
  themeConfig: {
    nav: nav('/zh-hant', copy),
    sidebar: sidebar('/zh-hant', copy),
    outline: { label: '本頁目錄', level: [2, 3] },
    lastUpdated: { text: '更新於' },
    docFooter: { prev: '上一頁', next: '下一頁' },
    darkModeSwitchLabel: '外觀',
    lightModeSwitchTitle: '切換到淺色',
    darkModeSwitchTitle: '切換到深色',
    sidebarMenuLabel: '選單',
    returnToTopLabel: '回到頂部',
    langMenuLabel: '更換語言',
    skipToContentLabel: '跳到正文',
    footer: {
      copyright: 'Copyright © 2026 DejavuMoe',
    },
  },
})
