import { defineConfig } from 'vitepress'
import { nav, sidebar, type NavCopy, type SidebarCopy } from './shared'

const copy: SidebarCopy & NavCopy = {
  guide: '指南',
  selfHosting: '部署',
  integration: '接入',
  reference: '参考',
  introduction: '简介',
  features: '功能',
  concepts: '工作方式',
  docker: 'Docker 部署',
  proxy: '反向代理',
  admin: '管理后台',
  notifications: '通知',
  captcha: '人机验证',
  backup: '备份与恢复',
  upgrade: '升级',
  twikoo: '从 Twikoo 迁移',
  faq: '常见问题',
  html: 'HTML 接入',
  sdk: 'JavaScript SDK',
  hugo: 'Hugo PaperMod',
  customCss: '自定义样式',
  smoji: 'Smoji 表情包',
  configuration: '配置参考',
  cli: '命令行',
  api: 'REST API',
  internalVersions: '内测记录（请勿使用）',
  earlierVersions: '更早的候选版本',
  versionCurrent: 'v0.3.5',
  versionLatest: '（最新）',
}

export const zh = defineConfig({
  title: 'Ecoku',
  description: '自托管，多站点，专注文字讨论。',
  lang: 'zh-Hans',
  markdown: {
    container: {
      tipLabel: '提示',
      warningLabel: '注意',
      dangerLabel: '警告',
      infoLabel: '说明',
      detailsLabel: '详细信息',
    },
  },
  themeConfig: {
    nav: nav('', copy),
    sidebar: sidebar('', copy),
    outline: { label: '本页目录', level: [2, 3] },
    lastUpdated: { text: '更新于' },
    docFooter: { prev: '上一页', next: '下一页' },
    darkModeSwitchLabel: '外观',
    lightModeSwitchTitle: '切换到浅色',
    darkModeSwitchTitle: '切换到深色',
    sidebarMenuLabel: '菜单',
    returnToTopLabel: '回到顶部',
    langMenuLabel: '更换语言',
    skipToContentLabel: '跳到正文',
    footer: {
      copyright: 'Copyright © 2026 DejavuMoe',
    },
  },
})
