(function () {
  "use strict";

  window.ECOKU_ADMIN_PROTOTYPE_FIXTURES = {
    sites: [
      { id: "docs", label: "文档站", defaultStatus: "pending" },
      { id: "garden", label: "数字花园", defaultStatus: "auto" }
    ],
    comments: [
      {
        id: 1041,
        siteId: "docs",
        mark: "/guides/sqlite-backup",
        parent: 0,
        status: "pending",
        deleted: false,
        username: "林峤",
        email: "lin@example.test",
        url: "https://example.test/lin",
        content: "备份步骤很清楚。是否可以补充一下停服后怎样校验备份文件完整性？",
        createdAt: "2026-08-13T02:18:00Z",
        updatedAt: "2026-08-13T02:18:00Z"
      },
      {
        id: 1042,
        siteId: "docs",
        mark: "/guides/reverse-proxy",
        parent: 913,
        status: "pending",
        deleted: false,
        username: "Mira",
        email: "mira@example.test",
        url: null,
        content: "回复上面的配置：如果只信任固定代理地址，容器重建后地址变化要怎样处理？",
        createdAt: "2026-08-13T03:06:00Z",
        updatedAt: "2026-08-13T03:06:00Z"
      },
      {
        id: 1043,
        siteId: "docs",
        mark: "/reference/embed-sdk",
        parent: 0,
        status: "pending",
        deleted: false,
        username: "访客 17",
        email: "visitor17@example.test",
        url: "https://example.test/profile",
        content: "<script>alert(\"x\")</script> 这段内容应当始终作为纯文本显示。",
        createdAt: "2026-08-13T04:25:00Z",
        updatedAt: "2026-08-13T04:25:00Z"
      },
      {
        id: 1044,
        siteId: "docs",
        mark: "/notes/self-hosting",
        parent: 0,
        status: "pending",
        deleted: false,
        username: "Northwind",
        email: "northwind@example.test",
        url: null,
        content: "希望升级文档里再明确写出 schema 版本高于程序时会拒绝启动。",
        createdAt: "2026-08-13T05:14:00Z",
        updatedAt: "2026-08-13T05:14:00Z"
      },
      {
        id: 1045,
        siteId: "docs",
        mark: "/reference/admin-api",
        parent: 0,
        status: "pending",
        deleted: false,
        username: "山茶",
        email: "camellia@example.test",
        url: null,
        content: "分页顺序在新评论写入后是否仍然稳定？文档里可以给出排序字段。",
        createdAt: "2026-08-13T06:02:00Z",
        updatedAt: "2026-08-13T06:02:00Z"
      },
      {
        id: 1034,
        siteId: "docs",
        mark: "/guides/sqlite-backup",
        parent: 0,
        status: "approved",
        deleted: false,
        username: "Owen",
        email: "owen@example.test",
        url: null,
        content: "在临时目录演练恢复的建议很实用。",
        createdAt: "2026-08-12T08:40:00Z",
        updatedAt: "2026-08-12T09:01:00Z"
      },
      {
        id: 1035,
        siteId: "docs",
        mark: "/reference/embed-sdk",
        parent: 0,
        status: "approved",
        deleted: false,
        username: "苏合",
        email: "suhe@example.test",
        url: "https://example.test/suhe",
        content: "用明确的页面 key 比自动猜测地址可靠很多。",
        createdAt: "2026-08-12T09:14:00Z",
        updatedAt: "2026-08-12T09:31:00Z"
      },
      {
        id: 1036,
        siteId: "docs",
        mark: "/notes/security-boundaries",
        parent: 0,
        status: "rejected",
        deleted: false,
        username: "anonymous",
        email: "anonymous@example.test",
        url: null,
        content: "重复发布的无关推广内容。",
        createdAt: "2026-08-12T10:02:00Z",
        updatedAt: "2026-08-12T10:18:00Z"
      },
      {
        id: 1037,
        siteId: "docs",
        mark: "/notes/security-boundaries",
        parent: 0,
        status: "approved",
        deleted: true,
        username: "已删除",
        email: null,
        url: null,
        content: "",
        createdAt: "2026-08-11T12:05:00Z",
        updatedAt: "2026-08-12T11:20:00Z"
      },
      {
        id: 2041,
        siteId: "garden",
        mark: "/journal/first-entry",
        parent: 0,
        status: "pending",
        deleted: false,
        username: "Pine",
        email: "pine@example.test",
        url: null,
        content: "自动通过站点里仍可能出现人工转为待审核的历史记录吗？",
        createdAt: "2026-08-13T03:40:00Z",
        updatedAt: "2026-08-13T03:40:00Z"
      },
      {
        id: 2038,
        siteId: "garden",
        mark: "/journal/first-entry",
        parent: 0,
        status: "approved",
        deleted: false,
        username: "苔",
        email: "moss@example.test",
        url: null,
        content: "纯文本评论读起来很安静。",
        createdAt: "2026-08-12T12:20:00Z",
        updatedAt: "2026-08-12T12:20:00Z"
      },
      {
        id: 2039,
        siteId: "garden",
        mark: "/journal/second-entry",
        parent: 0,
        status: "rejected",
        deleted: false,
        username: "Guest",
        email: "guest@example.test",
        url: null,
        content: "与页面内容无关的重复评论。",
        createdAt: "2026-08-12T13:22:00Z",
        updatedAt: "2026-08-12T13:30:00Z"
      },
      {
        id: 2040,
        siteId: "garden",
        mark: "/journal/second-entry",
        parent: 2038,
        status: "approved",
        deleted: true,
        username: "已删除",
        email: null,
        url: null,
        content: "",
        createdAt: "2026-08-12T14:12:00Z",
        updatedAt: "2026-08-12T15:44:00Z"
      }
    ]
  };
})();
