labels:
  platform: linux/amd64
  backend: docker
  role: forgejo-local
  server: netcup-rs1000

when:
  event: tag
  ref: refs/tags/v*

steps:
  - name: publish-amd64
    image: woodpeckerci/plugin-docker-buildx:6.1.0
    privileged: true
    settings:
      registry:
        from_secret: forgejo_registry
      repo:
        from_secret: forgejo_image
      username:
        from_secret: forgejo_registry_user
      password:
        from_secret: forgejo_registry_token
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_TAG}-amd64
      buildkit_oci_max_parallelism: 1
      build_args:
        - ECOKU_VERSION=${CI_COMMIT_TAG}
        - ECOKU_REVISION=${CI_COMMIT_SHA}
        - ECOKU_SOURCE=${CI_REPO_URL}
      pull_image: true
      provenance: mode=max

depends_on:
  - test

concurrency:
  limit: 1
  group: ecoku-image-amd64
